### ISSUE TITLE
Slides Overlapping

### ISSUE THREAD

**Issue by dv247** [iosscripts/iosslider#184]
We have an issue where the slides are overlapping using the latest version of iosslider 1.1.49. This was working previously with version 1.1.32. Any ideas as we require a gap between the slides?
The slider also conflicts with the 'sharethis' social share button.
![boxes_ok](https://f.cloud.github.com/assets/3243767/59718/e0845058-5bdf-11e2-8b80-1a2d0ebff4c0.jpg)
![boxes_overlapping](https://f.cloud.github.com/assets/3243767/59719/e0877a12-5bdf-11e2-8e93-2c63846c2278.jpg)

**Comment by marcwhitbread** [comment]
Hey, that's an issue I found and fixed in v1.1.53. Grab it here: https://github.com/iosscripts/iosSlider/archive/master.zip

If that fixes your issue, let me know.

**Comment by neilkyoung** [comment]
Brilliant - That worked!

Thank you very much for your prompt response! :-)

**Comment by dv247** [comment]
Thanks for that. However, we're still encountering an error when this is on the same page as the 'sharethis' social share code in ie8/ie9. Any ideas?

**Comment by marcwhitbread** [comment]
Please keep these issues focused. sharethis is unrelated to the slide overlap issue. Also, I asked you a few questions via email to which I received no reply.

If you wish to discuss the sharethis issue on here, create a new issue for it.

**Comment by dv247** [comment]
Hi, I'll create a new issue. Still awaiting the email.

**Comment by brandonfabcom** [comment]
Amazing .... What was causing it?
