### ISSUE TITLE
Big gap in the html content flow under the slider

### ISSUE THREAD

**Issue by stephaneeybert** [iosscripts/iosslider#24]
I implemented the slider and it works quite nicely :-)

But there is a big empty gap in the html content flow under the slider.

This occurs on Firefox 12.0 on my Linux pc and on iOS 5 on my iPod Touch.

It is solved, but not on my iPod Touch, only on my pc, with the following style:

  display: inline;

as in:

.elearning_exercise_page_tabs {
  position: relative;
  top: 0;
  left: 0;
  overflow: hidden;
  display: inline;
}

Here is my full implementation:

<style type="text/css">
.elearning_exercise_page_tabs {
  position: relative;
  top: 0;
  left: 0;
  overflow: hidden;
  display: inline;
}
.elearning_exercise_page_tabs .slider {
  width: 100%;
  height: 100%;
}
.elearning_exercise_page_tabs .elearning_exercise_page_tab {
  float: left;
}
</style>

<script src='$gJsUrl/jquery/jquery.easing.1.3.js' type='text/javascript'></script>

<script type = 'text/javascript' src = '$gJsUrl/jquery/iosSlider-0.9.4.3b/jquery.iosslider.min.js'></script>

<script>
$(document).ready(function() {
  $('.elearning_exercise_page_tabs').iosSlider({
    desktopClickDrag: true,
    infiniteSlider: true
  });
});
</script>

Kind Regards,

Stephane

**Comment by stephaneeybert** [comment]
I could work around the gap with the following style:

height: 50px;

as in:

.elearning_exercise_page_tabs {
  position: relative;
  top: 0;
  left: 0;
  overflow: hidden;
  height: 50px;
}

But I'm not so happy with it as it is hard coded and may conflict if the slide content is styled bigger by the end user of the cms.

Kind Regards,

Stephane

**Comment by iosscripts** [comment]
At the moment, a height value is needed to be specified on the outer div of the slider for it to be rendered properly. I will log this as a possible enhancement. Good find! :D

**Comment by stephaneeybert** [comment]
Sure :-) Your slider is really good !

**Comment by dechowdev** [comment]
I don't know if this is a plausible workaround... But i found that when i wanted to use the slider with a dynamic height. I could simply style the iosSlider container as such with jQuery and it would work: 

$(".iosSlider").css("height", "100%");

The slider expands "dynamically" to fill the content that is fed in the individual slide div's. Hope it makes sense.

**Comment by stephaneeybert** [comment]
I tried your workaround and it partially worked. It indeed got rid of the gap, but the last item in the list was "wrapped on the next line". So I reverted back to my fixed hard coded height which displays the items on one line only.

**Comment by dechowdev** [comment]
Im also having issues with the workaround in itself. Mostly it is working to get a dynamic height sort of.
But then again it's not a workaround i would strongly recommend since it could carry bugs along...

As an example. A line in the div might be cut off.

@iosscripts What is recommended practice? If we have HTML content we want to display in slide's with a dynamic height?

**Comment by iosscripts** [comment]
This has been requested a few times now. @Dechowmedia, I don't have a good answer for this right now but I will work on building the functionality into the script. I will try to get you more details today/tomorrow. 

Retagging as a high priority enhancement.

**Comment by dechowdev** [comment]
I also found that if you have a dynamic height on the individual slides. Such as height:auto; - the slider will break in chrome and display the slides as if they were display:block;

**Comment by jamesryanbell** [comment]
Has there been any update on this?

**Comment by iosscripts** [comment]
Still working on a solution. End of the week hopefully!

**Comment by iosscripts** [comment]
Please take a look at v0.9.4.6. I just committed it to the master branch (it's not tagged or in downloads yet). Please let me know if this change solves your issue.

**Comment by stephaneeybert** [comment]
I looked around on the GitHub project page to download the code, but failed to find the stuff.. :-)

You would give me a hint ?

Thank you.

**Comment by dechowdev** [comment]
@stephaneeybert see the above reference to the commit :) (https://github.com/iosscripts/iosSlider/issues/24#commits-ref-0cce80d)

I'm still having issues of sort but ill try out a auto height maybe? or should it work with an undefined height?
What issue should the commit fix? The undefined height?

Best
Lucas

**Comment by iosscripts** [comment]
I'm not sure. I tested against the following: 

<pre><code>.iosSlider { position: relative; top: 0; left: 0; overflow: hidden; } 
.iosSlider .slider { width: 100%; height: 100%; } 
.iosSlider .slider .slide { float: left; } 
</code></pre>


With no height defined, it was automatically collapsing the height correctly for me.

Can you provide your css if it is different? I would like it to work for as many cases as possible.

**Comment by stephaneeybert** [comment]
Sorry guys, I'm travelling at the moment. hard to test anything.

**Comment by iosscripts** [comment]
Month old, no new info provided. Will reopen if new info provided.
